### ISSUE TITLE
Upstream module missing?

### ISSUE THREAD

**Issue by SWSAmor** [tarantool/gentoo-overlay#11]
Maybe i screwed up something but the tarantool upstream module is not working for me:
nginx: [emerg] unknown directive "tnt_pass" in /etc/nginx/nginx.conf:162

Are there any additional modules needed?

NGINX_MODULES_HTTP="access auth_basic autoindex browser charset empty_gif fastcgi geo gzip limit_conn limit_req lua map memcached proxy referer rewrite scgi split_clients ssi upstream_check upstream_ip_hash upstream_keepalive upstream_tarantool userid uwsgi"

Or any suggestion?

Thanks.

**Comment by Totktonada** [comment]
Do you load the module?

```
load_module "modules/ngx_http_tnt_module.so";
```

**Comment by SWSAmor** [comment]
Thank you it's working! 👍 
(Sorry i didn't see the load_module in any examples.)

**Comment by Totktonada** [comment]
Added warning in c230f907.
