### ISSUE TITLE
How to run tarantool from init.d ?

### ISSUE THREAD

**Issue by SWSAmor** [tarantool/gentoo-overlay#16]
I tried to run tarantool Tarantool from init.d but i got this:
> * Starting tarantool ...
>Instance tarantool is not found in /etc/tarantool/instances.available                                                                           [ !! ]
> * ERROR: tarantool failed to start

I have instances in /etc/tarantool/instances.available but not with that name. I saw there is a ${RC_SVCNAME} variable in the init script, but where could i set this? What is the best practice for that? conf.d? env.d? What if i have more instances? 
I'd like to do this in the recommended way. ;-)
Thx.

**Comment by Totktonada** [comment]
Symlink it all :)

```
$ ll /etc/init.d/tarantool-servicename 
lrwxrwxrwx 1 root root 9 Jul 19 00:09 /etc/init.d/tarantool-servicename -> tarantool
```

```
cat /etc/tarantool/instances.available/tarantool-servicename.lua 
package.cpath = package.cpath .. ';/home/myuser/.luarocks/lib/lua/5.1/?.so'

local app = require('myservicename.request')
process_request = app.process_request
```

```
# ll /etc/tarantool/instances.enabled/tarantool-servicename.lua 
lrwxrwxrwx 1 root root 43 Jul 19 00:11 /etc/tarantool/instances.enabled/tarantool-servicename.lua -> ../instances.available/tarantool-servicename.lua
```

**Comment by Totktonada** [comment]
We should print this information in post-install phase, so please leave the issue open.

**Comment by SWSAmor** [comment]
So as the network in the install guide:
> root #cd /etc/init.d
> root #ln -s tarantool tarantool-yourmodule
> root #rc-update add tarantool-yourmodule default
That's cool. Thank you. 👍 
Runs successfully, but i have a problem. That service doesn't stop ever:
> /etc/init.d/tarantool-core stop
> * WARNING: tarantool-core is already stopped

And i haven't any instances.enabled dir. What is it for? Everything is worked without it. Should i create it?
I created the dir and symlinks by hand but the service never stops still. Maybe because you use systemd but i'm on openrc. Or not. :-)

**Comment by SWSAmor** [comment]
Weird. After some start-kill combos i tried the restart and noticed is working. Now start-stop is working too. 
>/etc/init.d/tarantool-core restart
> * Checking tarantool configuration ...
>File '/etc/tarantool/instances.available/tarantool-core.lua' is OK                                                                              [ ok ]
> * Stopping tarantool-core ...
>Stopping instance...                                                                                                                            [ ok ]
> * Starting tarantool-core ...
>Starting instance...                                                                                                                            [ ok ]

What happened?

**Comment by Totktonada** [comment]
The [documentation](https://tarantool.org/doc/1.7/book/administration.html#configuration-for-tarantoolctl) is confusing for me, but it seems all what you need with openrc / systemd is /etc/tarantool/instances.available/*. Old Debians [seems](https://github.com/tarantool/tarantool/blob/13874d4c953085f8b82506f67429af7b22928396/extra/dist/tarantool.init#L48) to have ability to start / stop tarantool services in the batch specified in instances.enabled (or other dir pointed by instance_dir in sysconfig, see the manual above). Also a default instance_dir (which will be used in case of absence of the sysconfig) can be instances.available or instance.enabled in dependence of WITH_SYSVINIT macro, check [CMakeLists.txt](https://github.com/tarantool/tarantool/blob/b37fc52e1bd8e941af4524f740546a42d9d132ec/extra/dist/CMakeLists.txt#L41). It is instances.available for my Gentoo/OpenRC case. I’ll open issue to doc, that need to be clarified.

**Comment by Totktonada** [comment]
Not sure what to do with non-stoppable tarantool :) But it is definitelly not a problem of init scripts, since now it works. Nothing to say w/o reproducable case, sorry.

**Comment by Totktonada** [comment]
I changed einfo to elog (will be displayed by default) and fixed information about an intance creation.

**Comment by Totktonada** [comment]
That issue triggers me to propose more strict algorithm of finding an instance directory to the documentation for system administrators. That was in my list of non-important tasks all this months, but now I made the PR :)

https://github.com/tarantool/doc/pull/393

@SWSAmor So, thanks for pointing us to that ambiguous thing in tarantool configuration process.
