### ISSUE TITLE
Couldn't download

### ISSUE THREAD

**Issue by SWSAmor** [tarantool/gentoo-overlay#17]
I got this:
> !!! Fetched file: tarantool-1.7.6.0.tar.gz VERIFY FAILED!
> !!! Reason: Filesize does not match recorded size
> !!! Got:      537
> !!! Expected: 16289206
> Refetching... File renamed to '/usr/portage/distfiles/tarantool-1.7.6.0.tar.gz._checksum_failure_.4c1xhf2o'

**Comment by Totktonada** [comment]
Thanks for the report. We’ll wait for resolve the https://github.com/tarantool/tarantool/issues/3049 issue.

**Comment by Totktonada** [comment]
The file is now downloadable. Fixed.
