### ISSUE TITLE
ICU needed

### ISSUE THREAD

**Issue by SWSAmor** [tarantool/gentoo-overlay#18]
I made a new install on a new server and I get this:
> CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
>  Could NOT find ICU (missing: ICU_INCLUDE_DIR ICU_LIBRARY_I18N
>  ICU_LIBRARY_UC)

I solved it with a:
> emerge -1 icu

but i think a dependency would be good. Would you fix that?

**Comment by Totktonada** [comment]
Thanks, I’ll fix it soon.

**Comment by SWSAmor** [comment]
Thx, you're great!

**Comment by Totktonada** [comment]
Done.
