### ISSUE TITLE
Update versioning

### ISSUE THREAD

**Issue by SWSAmor** [tarantool/gentoo-overlay#19]
As far as i know the Tarantool versioning is changed. Would you update the overlay to reflect the changes?

**Comment by Totktonada** [comment]
It was blocked by https://github.com/tarantool/tarantool/issues/2827 . Yes, I’ll do.

**Comment by Totktonada** [comment]
Hmm, I remembered that there is another blocker: https://github.com/tarantool/tarantool/issues/3308

**Comment by SWSAmor** [comment]
Thank you.
