### ISSUE TITLE
/var/run/tarantool needed

### ISSUE THREAD

**Issue by SWSAmor** [tarantool/gentoo-overlay#20]
The /var/run/tarantool directory is deleted on every restart. I should remake it by hand.

`Start failed: builtin/box/console.lua:382: failed to create server unix/:/var/run/tarantool/tarantool-core.control: No such file or directory`

I don't know how it could be solved usually, but maybe in the init.d script?

**Comment by Totktonada** [comment]
I see something like that, but every restart of the system. Need to investigate, sure.

**Comment by SWSAmor** [comment]
Sry, every restart of the system, not Tarantool.

**Comment by ipfedor** [comment]
+1 on windows10 ubuntu subsystem, after each restart system
root@ILLIAK:~# sudo tarantoolctl start users
Starting instance users...
Run console at unix/:/var/run/tarantool/users.control
Start failed: builtin/box/console.lua:382: failed to create server unix/:/var/run/tarantool/users.control: No such file or directory
root@ILLIAK:~# ls /var/run/tarantool/
ls: cannot access '/var/run/tarantool/': No such file or directory

**Comment by Totktonada** [comment]
It seems /etc/init.d/opentmpfiles* can do this. Maybe we need to install /usr/lib/tmpfiles.d/tarantool.conf (based on extra/dist/tarantool.tmpfiles.conf.in) instead of using keepdir.

**Comment by SWSAmor** [comment]
This is a problem still in 1.10.2.127 with openrc.

**Comment by SWSAmor** [comment]
I made a file (as you wrote):
`cat /etc/tmpfiles.d/tarantool.conf`
`d /var/run/tarantool 0775 tarantool tarantool`
and problem solved.

**Comment by D-Y-V** [comment]
Folks, please fix it. Startup script SHOULD create required env for application.
Please, implement start as 

start() {
        mkdir -p /var/run/tarantool
        chown tarantool:tarantool /var/run/tarantool
        ebegin "Starting ${RC_SVCNAME}"

        ${command} start ${RC_SVCNAME}

        eend $?
}

Thanks alot.

**Comment by D-Y-V** [comment]
This bug reported on 9 Apr 2018. No maintainers?.......No one fix?  Strange.....

**Comment by Totktonada** [comment]
I'll fix. Sorry for the delay.

**Comment by D-Y-V** [comment]
> I'll fix. Sorry for the delay.

Thanks alot!!!!
