### ISSUE TITLE
nginx 1.14

### ISSUE THREAD

**Issue by SWSAmor** [tarantool/gentoo-overlay#23]
Could you update nginx to version 1.14? 
It is stable in the main tree.

**Comment by Totktonada** [comment]
Added 1.14.0-r3 (stable) and 1.15.3 (unstable). Removed 1.13.3. Updated tarantool upstream module to 2.7.

**Comment by Totktonada** [comment]
Fixed in 2c803186c290bccfceff58701d5a489eec1566db.

**Comment by SWSAmor** [comment]
Both working great. Thank you.
