### ISSUE TITLE
Update dev-lua/http

### ISSUE THREAD

**Issue by SWSAmor** [tarantool/gentoo-overlay#24]
Happy new year! :-)

It seems the dev-lua/http need some update:
>  * Fetching https://github.com/tarantool/http ...
> git fetch https://github.com/tarantool/http +refs/heads/tarantool-1.7:refs/heads/tarantool-1.7
> fatal: Couldn't find remote ref refs/heads/tarantool-1.7
>  * ERROR: dev-lua/http-9999::tarantool failed (unpack phase):
>  *   Unable to fetch from any of EGIT_REPO_URI

Please fix it. Thx.

**Comment by Totktonada** [comment]
Thank you!

Fixed.
