### ISSUE TITLE
PostgreSQL package

### ISSUE THREAD

**Issue by SWSAmor** [tarantool/gentoo-overlay#25]
Hi! Could you make an ebuild for https://github.com/tarantool/pg ?

**Comment by Totktonada** [comment]
Done.

Ebuilds for modules are quite simple and mostly can be created with just copying one of existing module ebuild, fixing urls and description, maybe dependencies. Your can avoid waiting for me and create all needed ebuilds, then send PRs.

**Comment by SWSAmor** [comment]
You're the greatest. Thank you.
(Sry I'm not too experienced 🐑 in that and prefer waiting if you don't mind.)
