### ISSUE TITLE
Compile error in httpc.c

### ISSUE THREAD

**Issue by SWSAmor** [tarantool/gentoo-overlay#26]
Tarantool 1.10.2.1 compiled perfectly in November, last year. Now I got this on all servers:

> ...
[ 22%] Building C object src/CMakeFiles/server.dir/httpc.c.o
cd /var/tmp/portage/dev-db/tarantool-1.10.2.1/work/tarantool-1.10.2.1_build/src && /usr/bin/x86_64-pc-linux-gnu-gcc -DCORO_ASM -DLUAJIT_SMART_STRINGS=1 -DNDEBUG -DNVALGRIND -DNVALGRIND=1 -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS=1 -D__STDC_FORMAT_MACROS=1 -D__STDC_LIMIT_MACROS=1 -I/var/tmp/portage/dev-db/tarantool-1.10.2.1/work/tarantool-1.10.2.1/src -I/var/tmp/portage/dev-db/tarantool-1.10.2.1/work/tarantool-1.10.2.1_build/src -I/var/tmp/portage/dev-db/tarantool-1.10.2.1/work/tarantool-1.10.2.1/src/lib -I/var/tmp/portage/dev-db/tarantool-1.10.2.1/work/tarantool-1.10.2.1/src/lib/small -I/var/tmp/portage/dev-db/tarantool-1.10.2.1/work/tarantool-1.10.2.1/src/lib/small/third_party -I/var/tmp/portage/dev-db/tarantool-1.10.2.1/work/tarantool-1.10.2.1 -I/var/tmp/portage/dev-db/tarantool-1.10.2.1/work/tarantool-1.10.2.1/third_party/zstd/lib -I/var/tmp/portage/dev-db/tarantool-1.10.2.1/work/tarantool-1.10.2.1/third_party/zstd/lib/common -I/var/tmp/portage/dev-db/tarantool-1.10.2.1/work/tarantool-1.10.2.1_build/third_party -I/var/tmp/portage/dev-db/tarantool-1.10.2.1/work/tarantool-1.10.2.1/third_party -I/var/tmp/portage/dev-db/tarantool-1.10.2.1/work/tarantool-1.10.2.1/third_party/coro -I/var/tmp/portage/dev-db/tarantool-1.10.2.1/work/tarantool-1.10.2.1/third_party/luajit/src -I/var/tmp/portage/dev-db/tarantool-1.10.2.1/work/tarantool-1.10.2.1/src/lib/msgpuck -I/var/tmp/portage/dev-db/tarantool-1.10.2.1/work/tarantool-1.10.2.1/third_party/libutil_freebsd   -march=nehalem -O2 -pipe -fexceptions -funwind-tables -fno-omit-frame-pointer -fno-stack-protector -fno-common -fopenmp -msse2 -std=c11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-format-truncation -fno-gnu89-inline -Wno-cast-function-type  -ggdb -O2   -o CMakeFiles/server.dir/httpc.c.o -c /var/tmp/portage/dev-db/tarantool-1.10.2.1/work/tarantool-1.10.2.1/src/httpc.c
/var/tmp/portage/dev-db/tarantool-1.10.2.1/work/tarantool-1.10.2.1/src/httpc.c: In function ‘httpc_execute’:
/var/tmp/portage/dev-db/tarantool-1.10.2.1/work/tarantool-1.10.2.1/src/httpc.c:337:2: error: duplicate case value
  case CURLE_PEER_FAILED_VERIFICATION:
  ^~~~
/var/tmp/portage/dev-db/tarantool-1.10.2.1/work/tarantool-1.10.2.1/src/httpc.c:336:2: note: previously used here
  case CURLE_SSL_CACERT:
  ^~~~
/var/tmp/portage/dev-db/tarantool-1.10.2.1/work/tarantool-1.10.2.1/src/httpc.c: At top level:
cc1: warning: unrecognized command line option ‘-Wno-cast-function-type’
make[2]: *** [src/CMakeFiles/server.dir/build.make:444: src/CMakeFiles/server.dir/httpc.c.o] Error 1
make[2]: Leaving directory '/var/tmp/portage/dev-db/tarantool-1.10.2.1/work/tarantool-1.10.2.1_build'
make[1]: *** [CMakeFiles/Makefile2:750: src/CMakeFiles/server.dir/all] Error 2
make[1]: Leaving directory '/var/tmp/portage/dev-db/tarantool-1.10.2.1/work/tarantool-1.10.2.1_build'
make: *** [Makefile:152: all] Error 2
>  * ERROR: dev-db/tarantool-1.10.2.1::tarantool failed (compile phase):
>  *   emake failed

I reemerged curl, gcc, glibc and so, but same result.
curl has ssl and openssl use flags.

Please help!

**Comment by Totktonada** [comment]
Yep, old tarantool versions don't have the fix for the new curl versions. We can add a patch: https://github.com/tarantool/tarantool/commit/02da15f7109b8bb7921eb97a751607b9dd2885b2 . You can add it to user patches for now. Or integrate to the repo and send a PR.

**Comment by Totktonada** [comment]
Added 1.10.2.127, which builds cleanly.

**Comment by SWSAmor** [comment]
It builds successfully. Thank you.
