### ISSUE TITLE
dev-lua/http dependency

### ISSUE THREAD

**Issue by SWSAmor** [tarantool/gentoo-overlay#29]
It seems http 2.0 has a dependency:

`Start failed: /usr/share/tarantool/http/server/tsgi_adapter.lua:3: module 'checks' not found`

That one from luarocks solved the problem:

`checks
   1.0-1 (rockspec) - https://rocks.moonscript.org
   1.0-1 (src) - https://rocks.moonscript.org`

**Comment by D-Y-V** [comment]
Same result

$ tarantoolctl connect 3301
connected to localhost:3301
localhost:3301>  http_server = require('http.server').new('0.0.0.0', 8080)
---
- error: "/usr/share/tarantool/http/server/tsgi_adapter.lua:3: module 'checks' not
    found:\n\tno field package.preload['checks']\n\tno file '/checks.lua'\n\tno file
    '/checks/init.lua'\n\tno file '/checks.so'\n\tno file '/.rocks/share/tarantool/checks.lua'\n\tno
    file '/.rocks/share/tarantool/checks/init.lua'\n\tno file '/.rocks/lib/tarantool/checks.so'\n\tno
    file '/usr/local/share/tarantool/checks.lua'\n\tno file '/usr/local/share/tarantool/checks/init.lua'\n\tno
    file '/usr/share/tarantool/checks.lua'\n\tno file '/usr/share/tarantool/checks/init.lua'\n\tno
    file '/usr/lib64/lua/luarocks/share/tarantool/checks.lua'\n\tno file '/usr/lib64/lua/luarocks/share/tarantool/checks/init.lua'\n\tno
    file '/usr/local/share/lua/5.1/checks.lua'\n\tno file '/usr/local/share/lua/5.1/checks/init.lua'\n\tno
    file '/usr/share/lua/5.1/checks.lua'\n\tno file '/usr/share/lua/5.1/checks/init.lua'\n\tno
    file '/usr/lib64/lua/luarocks/share/lua/5.1/checks.lua'\n\tno file '/usr/lib64/lua/luarocks/share/lua/5.1/checks/init.lua'\n\tno
    file '/usr/local/lib64/tarantool/checks.so'\n\tno file '/usr/lib64/tarantool/checks.so'\n\tno
    file '/usr/lib64/lua/luarocks/lib/tarantool/checks.so'\n\tno file '/usr/local/lib64/lua/5.1/checks.so'\n\tno
    file '/usr/lib64/lua/5.1/checks.so'\n\tno file '/usr/lib64/lua/luarocks/lib/lua/5.1/checks.so'"
...

localhost:3301>

**Comment by D-Y-V** [comment]
equery f http
 * Searching for http ...
 * Contents of dev-lua/http-9999:
/usr
/usr/lib64
/usr/lib64/tarantool
/usr/lib64/tarantool/http
/usr/lib64/tarantool/http/lib.so
/usr/share
/usr/share/doc
/usr/share/doc/http-9999
/usr/share/doc/http-9999/AUTHORS.bz2
/usr/share/doc/http-9999/README.md.bz2
/usr/share/tarantool
/usr/share/tarantool/http
/usr/share/tarantool/http/VERSION.lua
/usr/share/tarantool/http/codes.lua
/usr/share/tarantool/http/mime_types.lua
/usr/share/tarantool/http/nginx_server
/usr/share/tarantool/http/nginx_server/init.lua
/usr/share/tarantool/http/router
/usr/share/tarantool/http/router/fs.lua
/usr/share/tarantool/http/router/init.lua
/usr/share/tarantool/http/router/matching.lua
/usr/share/tarantool/http/router/middleware.lua
/usr/share/tarantool/http/router/request.lua
/usr/share/tarantool/http/router/response.lua
/usr/share/tarantool/http/server
/usr/share/tarantool/http/server/init.lua
/usr/share/tarantool/http/server/tsgi_adapter.lua
/usr/share/tarantool/http/tsgi.lua
/usr/share/tarantool/http/utils.lua
