### ISSUE TITLE
new ebuild for www-servers/nginx-1.17.8.ebuild

### ISSUE THREAD

**Issue by D-Y-V** [tarantool/gentoo-overlay#30]
Request new ebuild for nginx.

[nginx-1.17.8.ebuild.tar.gz](https://github.com/tarantool/gentoo-overlay/files/4113660/nginx-1.17.8.ebuild.tar.gz)

With best wishes)

**Comment by Totktonada** [comment]
It seems you missed this block:

```
	nginx_modules_http_upstream_tarantool? (
		dev-libs/msgpuck:2=
		dev-libs/yajl:=
	)
```

Anyway, I'll check and update it soon.
