### ISSUE TITLE
queue 1.0.6

### ISSUE THREAD

**Issue by SWSAmor** [tarantool/gentoo-overlay#34]
I'd like to upgrade to https://github.com/tarantool/queue/releases/tag/1.0.6
Would you refresh the overlay?

**Comment by SWSAmor** [comment]
Maybe we need just a symbolic link queue-1.0.6.ebuild to queue-9999.ebuild ?

**Comment by Totktonada** [comment]
Yep. I'll add.

**Comment by SWSAmor** [comment]
Thank you.
